package odd.client.model;

public enum Category {
    GENERAL_FOOD, BEVERAGE, SNACKS,
    MEAT, VEGETABLE, DAIRY,
    DAILY_NECESSITIES, ICE_CREAM,
    REFRIGERATED_FOOD, SEAFOOD,
    PREPARED_FOOD, MEAL_KITS, FRESH_FOOD,
    ALCOHOLIC_BEVERAGES, CONVENIENCE_FOOD, BEAUTY
}
